---
title: Data & Injury Narratives
output: html_document
---
***
### The SeriousInjury package includes five data frames:<br><br>


#### '**WhaleData**' is raw data for all whale injury cases. Injury descriptions are in the 'Narrative' field and assessed health status are in the 'Health.status' field.<br><br>


#### '**data.entangle**' and '**data.vessel**' are known-outcome entanglements and vessel strikes used to build Random Forest (RF) models. These include cases assigned a 'Health.status'="DEAD.DECLINE" or "RECOVERED". These data exclude cases where human intervention to remove entanglements occurred.<br><br> 


#### '**data.test.entangle**' and '**data.test.vessel**' include cases with 'Health.status'="UNKNOWN" and are used with the predict() function and the RF objects 'ModelEntanglement' and 'ModelVessel' to assign cases to "DEAD.DECLINE" or "RECOVERED".<br><br>


#### Example 'Narrative' from which model covariates are derived. Some key words and phrases in the narrative that are coded as presence / absence covariates include 'cyamids', 'fluke', 'peduncle', 'grey skin', 'poor'. <br><br>

#### "Entanglement injuries at fluke insertions and peduncle with associated cyamids at injured areas and on head. Grey skin and overal poor appearance."<br><br>

```

# Example code to identify the covariate 'decline' from injury narratives in data.frame 'WhaleData'.
#   function InjuryCovariates() applied to data.frame 'WhaleData'
#    data.frame narrative field must be named 'Narrative' for use with InjuryCovariates().
#     use function 'grepl' to search for words/phrases in 'Narrative'.
#      code covariates numerically as 1/0, aligned with their TRUE/FALSE (=presence/absence) state.

# Evidence of a health decline? 
#  Search 'Narrative' for words/phrases associated with health declines.
    
    decline <- grepl(" abnormal|chronic|deteriorat|fair|
     compromise|scoliosis|deform|cyamid|lice|lethargic|
      lesion|discolor|diatom|poor cond|poor health|poor body|
       poor over|poor skin|rake|skin|slough|thin |emaciated|malnourish|
        underweight|starv|mobility", WhaleData$Narrative, ignore.case=T)
    
    decline <- as.numeric(lapply(decline, as.numeric))
     decline
    
# Use InjuryCovariates() to append all covariates to each row of 'WhaleData' 
    
    head(WhaleData)

    new.data.frame <- InjuryCovariates(WhaleData)

    head(new.data.frame)
```

